version: '3.8'

services:
  cineprive-app:
    build: .
    container_name: cineprive-app
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TMDB_API_KEY=VOTRE_CLE_TMDB_ICI
